name: Python package

on: push

jobs:
  build:

    runs-on: ubuntu-18.04
    strategy:
      matrix:
        python-version: [2.7.18]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        sudo apt-get update && sudo apt-get install virtualenv gettext
    - name: Run setup
      run: |
        CREDENTIALS=(
            # Server mode: Local development mode with dummy email infrastructure.
            "2"
            # Install requirements for unittesting?
            "n"
            # Server domain
            "localhost:8000"
            # Admin e-mail (default)
            ""
            # Support e-mail (default)
            ""
            # Inforequest unique e-mail (default)
            ""
            # Default from e-mail (default)
            ""
            # Obligee dummy e-mail
            "obilgee@chcemvediet.sk"
            # Unique cache key prefix
            "www-chcemvediet-sk"
            # comment
            "y"
            # comment
            "y"
            # comment
            "y"
            # comment
            "y"
            # Admin password
            "admin"
            # comment
            ""
            # comment
            ""
            # comment
            ""
            # comment
            ""
            # comment
            ""
            # comment
            ""
            # Google OAuth Client ID (default)
            ""
            # Google OAuth Secret (default)
            ""
        )
        printf "%s\n" "${CREDENTIALS[@]}" | PYTHONUNBUFFERED=1 python setup.py
    - name: Test
      run: |
        env/bin/python manage.py test

