# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions
#simple

name: Python package

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-18.04
    strategy:
      matrix:
        python-version: [2.7.17, 2.7.18]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        pwd
        echo "where is python"
        which python
        which pip
        pip list
        printf "\n\n /opt/pip/list:"
        /opt/hostedtoolcache/Python/2.7.18/x64/bin/pip list
        sudo apt-get install gettext
        sudo apt-get update && sudo apt-get install virtualenv
        python -m pip install --upgrade pip
        printf "%s\n" \
            "1" \
            "n" \
            "localhost:8000" \
            "" \
            "" \
            "" \
            "" \
            "obilgee@chcemvediet.sk"\
            "www-chcemvediet-sk" \
            "n" \
            "n" \
            "n" \
            "n" \
            "admin" \
            "" \
            "" \
            "" \
            "" \
            "" \
            "" \
            "" \
            "" \
        | PYTHONUNBUFFERED=1 python setup.py
        pip list
    - name: Test
      run: |
        env/bin/python manage.py test

