name: Python package

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-18.04
    strategy:
      matrix:
        python-version: [2.7.18]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        sudo apt-get update && sudo apt-get install virtualenv gettext
        printf "%s\n" \
            "2" \
            "n" \
            "localhost:8000" \
            "" \
            "" \
            "" \
            "" \
            "obilgee@chcemvediet.sk"\
            "www-chcemvediet-sk" \
            "y" \
            "y" \
            "y" \
            "y" \
            "admin" \
            "" \
            "" \
            "" \
            "" \
            "" \
            "" \
            "" \
            "" \
        | PYTHONUNBUFFERED=1 python setup.py
        pip list
    - name: Test
      run: |
        env/bin/python manage.py test

