name: Testing project
on: push
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout repo
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 2.7.18
    - name: Install dependencies
      run: |
        sudo apt-get update && sudo apt-get install virtualenv gettext
    - name: Run setup
      run: |
        CONFIGURATION=(
            # Server mode: Local development mode with dummy email infrastructure.
            "2"
            # Install requirements for unittesting?
            "n"
            # Server domain
            "localhost:8000"
            # Admin e-mail (default)
            ""
            # Support e-mail (default)
            ""
            # Inforequest unique e-mail (default)
            ""
            # Default from e-mail (default)
            ""
            # Obligee dummy e-mail
            "obilgee@chcemvediet.sk"
            # Unique cache key prefix
            "www-chcemvediet-sk"
            # comment
            "y"
            # comment
            "y"
            # comment
            "y"
            # comment
            "y"
            # Admin password
            "admin"
            # comment
            ""
            # comment
            ""
            # comment
            ""
            # comment
            ""
            # comment
            ""
            # comment
            ""
            # Google OAuth Client ID (default)
            ""
            # Google OAuth Secret (default)
            ""
        )
        printf "%s\n" "${CREDENTIALS[@]}" | PYTHONUNBUFFERED=1 python setup.py
    - name: Run tests
      run: |
        env/bin/python manage.py test

